// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {desktop} from '../models';

export function CleanupUnusedUploadedImages():Promise<service.UploadedImageCleanup>;

export function CreateDayEntry(arg1:service.DayEntry):Promise<service.DayEntry>;

export function CreateIssue(arg1:service.Issue):Promise<service.Issue>;

export function CreateIssueEvent(arg1:string,arg2:service.IssueEvent):Promise<service.IssueEvent>;

export function CreateIssueTodo(arg1:string,arg2:service.IssueTodo):Promise<service.IssueTodo>;

export function CreateTempTask(arg1:service.TempTask):Promise<service.TempTask>;

export function CreateTempTaskEvent(arg1:number,arg2:service.TempTaskEvent):Promise<service.TempTaskEvent>;

export function Dashboard():Promise<service.Dashboard>;

export function DeleteDayEntry(arg1:number):Promise<Record<string, boolean>>;

export function DeleteIssue(arg1:string):Promise<Record<string, boolean>>;

export function DeleteIssueEvent(arg1:number):Promise<Record<string, boolean>>;

export function DeleteIssueTodo(arg1:number):Promise<Record<string, boolean>>;

export function DeleteTempTask(arg1:number):Promise<Record<string, boolean>>;

export function DeleteTempTaskEvent(arg1:number):Promise<Record<string, boolean>>;

export function DeleteUploadedImage(arg1:string):Promise<Record<string, boolean>>;

export function ExportIssueMarkdown(arg1:string):Promise<desktop.SaveResult>;

export function ExportJSON():Promise<desktop.SaveResult>;

export function ExportMarkdownZip():Promise<desktop.SaveResult>;

export function ExportTempTaskMarkdown(arg1:number):Promise<desktop.SaveResult>;

export function ExportWeekMarkdown(arg1:string):Promise<desktop.SaveResult>;

export function GenerateIssueSummary(arg1:string):Promise<service.IssueSummaryResponse>;

export function GenerateWeekDraft(arg1:string):Promise<service.WeeklyLog>;

export function GenerateWeekSummary(arg1:string):Promise<service.WeeklyLog>;

export function GetIssue(arg1:string):Promise<service.Issue>;

export function GetSettings():Promise<service.AppSettings>;

export function GetTempTask(arg1:number):Promise<service.TempTask>;

export function GetUploadedImageDataURL(arg1:string):Promise<service.UploadedImageData>;

export function GetWeek(arg1:string):Promise<service.WeekView>;

export function ImportJiraIssue(arg1:string):Promise<service.Issue>;

export function ListIssueEvents(arg1:string):Promise<Array<service.IssueEvent>>;

export function ListIssueTodos(arg1:string,arg2:boolean):Promise<Array<service.IssueTodo>>;

export function ListIssues(arg1:service.IssueFilter):Promise<Array<service.Issue>>;

export function ListTempTaskEvents(arg1:number):Promise<Array<service.TempTaskEvent>>;

export function ListTempTasks(arg1:service.TempTaskFilter):Promise<Array<service.TempTask>>;

export function ListWeeks():Promise<Array<service.WeeklyLog>>;

export function Search(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<service.SearchResult>>;

export function Today():Promise<service.TodayWorkflow>;

export function UpdateIssue(arg1:string,arg2:service.Issue):Promise<service.Issue>;

export function UpdateIssueEvent(arg1:number,arg2:service.IssueEvent):Promise<service.IssueEvent>;

export function UpdateIssueTodo(arg1:number,arg2:service.IssueTodo):Promise<service.IssueTodo>;

export function UpdateSettings(arg1:service.AppSettings):Promise<service.AppSettings>;

export function UpdateTempTask(arg1:number,arg2:service.TempTask):Promise<service.TempTask>;

export function UpdateTempTaskEvent(arg1:number,arg2:service.TempTaskEvent):Promise<service.TempTaskEvent>;

export function UpdateWeek(arg1:string,arg2:service.WeeklyLog):Promise<service.WeeklyLog>;

export function UploadImage(arg1:desktop.FileUpload):Promise<service.UploadedImage>;
