// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupUnusedUploadedImages() {
  return window['go']['desktop']['App']['CleanupUnusedUploadedImages']();
}

export function CreateDayEntry(arg1) {
  return window['go']['desktop']['App']['CreateDayEntry'](arg1);
}

export function CreateIssue(arg1) {
  return window['go']['desktop']['App']['CreateIssue'](arg1);
}

export function CreateIssueEvent(arg1, arg2) {
  return window['go']['desktop']['App']['CreateIssueEvent'](arg1, arg2);
}

export function CreateIssueTodo(arg1, arg2) {
  return window['go']['desktop']['App']['CreateIssueTodo'](arg1, arg2);
}

export function CreateTempTask(arg1) {
  return window['go']['desktop']['App']['CreateTempTask'](arg1);
}

export function CreateTempTaskEvent(arg1, arg2) {
  return window['go']['desktop']['App']['CreateTempTaskEvent'](arg1, arg2);
}

export function Dashboard() {
  return window['go']['desktop']['App']['Dashboard']();
}

export function DeleteDayEntry(arg1) {
  return window['go']['desktop']['App']['DeleteDayEntry'](arg1);
}

export function DeleteIssue(arg1) {
  return window['go']['desktop']['App']['DeleteIssue'](arg1);
}

export function DeleteIssueEvent(arg1) {
  return window['go']['desktop']['App']['DeleteIssueEvent'](arg1);
}

export function DeleteIssueTodo(arg1) {
  return window['go']['desktop']['App']['DeleteIssueTodo'](arg1);
}

export function DeleteTempTask(arg1) {
  return window['go']['desktop']['App']['DeleteTempTask'](arg1);
}

export function DeleteTempTaskEvent(arg1) {
  return window['go']['desktop']['App']['DeleteTempTaskEvent'](arg1);
}

export function DeleteUploadedImage(arg1) {
  return window['go']['desktop']['App']['DeleteUploadedImage'](arg1);
}

export function ExportIssueMarkdown(arg1) {
  return window['go']['desktop']['App']['ExportIssueMarkdown'](arg1);
}

export function ExportJSON() {
  return window['go']['desktop']['App']['ExportJSON']();
}

export function ExportMarkdownZip() {
  return window['go']['desktop']['App']['ExportMarkdownZip']();
}

export function ExportTempTaskMarkdown(arg1) {
  return window['go']['desktop']['App']['ExportTempTaskMarkdown'](arg1);
}

export function ExportWeekMarkdown(arg1) {
  return window['go']['desktop']['App']['ExportWeekMarkdown'](arg1);
}

export function GenerateIssueSummary(arg1) {
  return window['go']['desktop']['App']['GenerateIssueSummary'](arg1);
}

export function GenerateWeekDraft(arg1) {
  return window['go']['desktop']['App']['GenerateWeekDraft'](arg1);
}

export function GenerateWeekSummary(arg1) {
  return window['go']['desktop']['App']['GenerateWeekSummary'](arg1);
}

export function GetIssue(arg1) {
  return window['go']['desktop']['App']['GetIssue'](arg1);
}

export function GetSettings() {
  return window['go']['desktop']['App']['GetSettings']();
}

export function GetTempTask(arg1) {
  return window['go']['desktop']['App']['GetTempTask'](arg1);
}

export function GetUploadedImageDataURL(arg1) {
  return window['go']['desktop']['App']['GetUploadedImageDataURL'](arg1);
}

export function GetWeek(arg1) {
  return window['go']['desktop']['App']['GetWeek'](arg1);
}

export function GetWeekBounds() {
  return window['go']['desktop']['App']['GetWeekBounds']();
}

export function ImportJiraIssue(arg1) {
  return window['go']['desktop']['App']['ImportJiraIssue'](arg1);
}

export function ListIssueEvents(arg1) {
  return window['go']['desktop']['App']['ListIssueEvents'](arg1);
}

export function ListIssueTodos(arg1, arg2) {
  return window['go']['desktop']['App']['ListIssueTodos'](arg1, arg2);
}

export function ListIssues(arg1) {
  return window['go']['desktop']['App']['ListIssues'](arg1);
}

export function ListTempTaskEvents(arg1) {
  return window['go']['desktop']['App']['ListTempTaskEvents'](arg1);
}

export function ListTempTasks(arg1) {
  return window['go']['desktop']['App']['ListTempTasks'](arg1);
}

export function ListWeeks() {
  return window['go']['desktop']['App']['ListWeeks']();
}

export function Search(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['Search'](arg1, arg2, arg3, arg4);
}

export function Today() {
  return window['go']['desktop']['App']['Today']();
}

export function UpdateIssue(arg1, arg2) {
  return window['go']['desktop']['App']['UpdateIssue'](arg1, arg2);
}

export function UpdateIssueEvent(arg1, arg2) {
  return window['go']['desktop']['App']['UpdateIssueEvent'](arg1, arg2);
}

export function UpdateIssueTodo(arg1, arg2) {
  return window['go']['desktop']['App']['UpdateIssueTodo'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['desktop']['App']['UpdateSettings'](arg1);
}

export function UpdateTempTask(arg1, arg2) {
  return window['go']['desktop']['App']['UpdateTempTask'](arg1, arg2);
}

export function UpdateTempTaskEvent(arg1, arg2) {
  return window['go']['desktop']['App']['UpdateTempTaskEvent'](arg1, arg2);
}

export function UpdateWeek(arg1, arg2) {
  return window['go']['desktop']['App']['UpdateWeek'](arg1, arg2);
}

export function UploadImage(arg1) {
  return window['go']['desktop']['App']['UploadImage'](arg1);
}
